project:
  type: default
  output-dir: docs
  render:
    - index.qmd
    - logistic_selectivity.qmd
    - double_logistic_selectivity.qmd
    - spline_selectivity.qmd
    - timevarying_selectivity.qmd

filters:
  - filters/remove_embedded_markdown_source.lua

format:
  html:
    lightbox: false
    fig-link: false
    embed-resources: true
    toc: true
    number-sections: true
    theme: cosmo
    css: style.css
    code-fold: true
    code-summary: "Show R code"
    code-tools: false

execute:
  echo: true
  message: false
  warning: false
  freeze: true

bibliography: references.bib
