project:
  type: manuscript
  output-dir: _manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: double_logistic_selectivity.qmd
      title: "Double Logistic Selectivity"
    - notebook: logistic_selectivity.qmd
      title: "Standard Logistic Selectivity"
    - notebook: spline_selectivity.qmd
      title: "Spline-Based Selectivity"
    - notebook: timevarying_selectivity.qmd
      title: "Time-Varying 2D AR1 Selectivity"

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    css: style.css

execute:
  echo: false
  message: false
  warning: false
  freeze: true

bibliography: references.bib
